// Code generated by MockGen. DO NOT EDIT.
// Source: internal/restaurant/domain/repository/favorite_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/restaurant/domain/repository/favorite_repository.go -destination=internal/restaurant/mocks/mock_favorite_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Leon180/tabelogo-v2/internal/restaurant/domain/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFavoriteRepository is a mock of FavoriteRepository interface.
type MockFavoriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteRepositoryMockRecorder
	isgomock struct{}
}

// MockFavoriteRepositoryMockRecorder is the mock recorder for MockFavoriteRepository.
type MockFavoriteRepositoryMockRecorder struct {
	mock *MockFavoriteRepository
}

// NewMockFavoriteRepository creates a new mock instance.
func NewMockFavoriteRepository(ctrl *gomock.Controller) *MockFavoriteRepository {
	mock := &MockFavoriteRepository{ctrl: ctrl}
	mock.recorder = &MockFavoriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteRepository) EXPECT() *MockFavoriteRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockFavoriteRepository) CountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockFavoriteRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockFavoriteRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockFavoriteRepository) Create(ctx context.Context, favorite *model.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFavoriteRepositoryMockRecorder) Create(ctx, favorite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFavoriteRepository)(nil).Create), ctx, favorite)
}

// Delete mocks base method.
func (m *MockFavoriteRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFavoriteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFavoriteRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockFavoriteRepository) Exists(ctx context.Context, userID, restaurantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID, restaurantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFavoriteRepositoryMockRecorder) Exists(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFavoriteRepository)(nil).Exists), ctx, userID, restaurantID)
}

// FindByID mocks base method.
func (m *MockFavoriteRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFavoriteRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFavoriteRepository)(nil).FindByID), ctx, id)
}

// FindByRestaurantID mocks base method.
func (m *MockFavoriteRepository) FindByRestaurantID(ctx context.Context, restaurantID uuid.UUID) ([]*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRestaurantID", ctx, restaurantID)
	ret0, _ := ret[0].([]*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRestaurantID indicates an expected call of FindByRestaurantID.
func (mr *MockFavoriteRepositoryMockRecorder) FindByRestaurantID(ctx, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRestaurantID", reflect.TypeOf((*MockFavoriteRepository)(nil).FindByRestaurantID), ctx, restaurantID)
}

// FindByTag mocks base method.
func (m *MockFavoriteRepository) FindByTag(ctx context.Context, userID uuid.UUID, tag string) ([]*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTag", ctx, userID, tag)
	ret0, _ := ret[0].([]*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTag indicates an expected call of FindByTag.
func (mr *MockFavoriteRepositoryMockRecorder) FindByTag(ctx, userID, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTag", reflect.TypeOf((*MockFavoriteRepository)(nil).FindByTag), ctx, userID, tag)
}

// FindByUserAndRestaurant mocks base method.
func (m *MockFavoriteRepository) FindByUserAndRestaurant(ctx context.Context, userID, restaurantID uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndRestaurant", ctx, userID, restaurantID)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndRestaurant indicates an expected call of FindByUserAndRestaurant.
func (mr *MockFavoriteRepositoryMockRecorder) FindByUserAndRestaurant(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndRestaurant", reflect.TypeOf((*MockFavoriteRepository)(nil).FindByUserAndRestaurant), ctx, userID, restaurantID)
}

// FindByUserID mocks base method.
func (m *MockFavoriteRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockFavoriteRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockFavoriteRepository)(nil).FindByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockFavoriteRepository) Update(ctx context.Context, favorite *model.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFavoriteRepositoryMockRecorder) Update(ctx, favorite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFavoriteRepository)(nil).Update), ctx, favorite)
}
