// Code generated by MockGen. DO NOT EDIT.
// Source: internal/restaurant/domain/repository/restaurant_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/restaurant/domain/repository/restaurant_repository.go -destination=internal/restaurant/mocks/mock_restaurant_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Leon180/tabelogo-v2/internal/restaurant/domain/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRestaurantRepository is a mock of RestaurantRepository interface.
type MockRestaurantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantRepositoryMockRecorder
	isgomock struct{}
}

// MockRestaurantRepositoryMockRecorder is the mock recorder for MockRestaurantRepository.
type MockRestaurantRepositoryMockRecorder struct {
	mock *MockRestaurantRepository
}

// NewMockRestaurantRepository creates a new mock instance.
func NewMockRestaurantRepository(ctrl *gomock.Controller) *MockRestaurantRepository {
	mock := &MockRestaurantRepository{ctrl: ctrl}
	mock.recorder = &MockRestaurantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantRepository) EXPECT() *MockRestaurantRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRestaurantRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRestaurantRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRestaurantRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockRestaurantRepository) Create(ctx context.Context, restaurant *model.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, restaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRestaurantRepositoryMockRecorder) Create(ctx, restaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRestaurantRepository)(nil).Create), ctx, restaurant)
}

// Delete mocks base method.
func (m *MockRestaurantRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestaurantRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestaurantRepository)(nil).Delete), ctx, id)
}

// FindByCuisineType mocks base method.
func (m *MockRestaurantRepository) FindByCuisineType(ctx context.Context, cuisineType string, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCuisineType", ctx, cuisineType, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCuisineType indicates an expected call of FindByCuisineType.
func (mr *MockRestaurantRepositoryMockRecorder) FindByCuisineType(ctx, cuisineType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCuisineType", reflect.TypeOf((*MockRestaurantRepository)(nil).FindByCuisineType), ctx, cuisineType, limit, offset)
}

// FindByExternalID mocks base method.
func (m *MockRestaurantRepository) FindByExternalID(ctx context.Context, source model.RestaurantSource, externalID string) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternalID", ctx, source, externalID)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternalID indicates an expected call of FindByExternalID.
func (mr *MockRestaurantRepositoryMockRecorder) FindByExternalID(ctx, source, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternalID", reflect.TypeOf((*MockRestaurantRepository)(nil).FindByExternalID), ctx, source, externalID)
}

// FindByID mocks base method.
func (m *MockRestaurantRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRestaurantRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRestaurantRepository)(nil).FindByID), ctx, id)
}

// FindByLocation mocks base method.
func (m *MockRestaurantRepository) FindByLocation(ctx context.Context, lat, lng, radiusKm float64, limit int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLocation", ctx, lat, lng, radiusKm, limit)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLocation indicates an expected call of FindByLocation.
func (mr *MockRestaurantRepositoryMockRecorder) FindByLocation(ctx, lat, lng, radiusKm, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLocation", reflect.TypeOf((*MockRestaurantRepository)(nil).FindByLocation), ctx, lat, lng, radiusKm, limit)
}

// FindBySource mocks base method.
func (m *MockRestaurantRepository) FindBySource(ctx context.Context, source model.RestaurantSource, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySource", ctx, source, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySource indicates an expected call of FindBySource.
func (mr *MockRestaurantRepositoryMockRecorder) FindBySource(ctx, source, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySource", reflect.TypeOf((*MockRestaurantRepository)(nil).FindBySource), ctx, source, limit, offset)
}

// List mocks base method.
func (m *MockRestaurantRepository) List(ctx context.Context, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRestaurantRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRestaurantRepository)(nil).List), ctx, limit, offset)
}

// Search mocks base method.
func (m *MockRestaurantRepository) Search(ctx context.Context, query string, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRestaurantRepositoryMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRestaurantRepository)(nil).Search), ctx, query, limit, offset)
}

// Update mocks base method.
func (m *MockRestaurantRepository) Update(ctx context.Context, restaurant *model.Restaurant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, restaurant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRestaurantRepositoryMockRecorder) Update(ctx, restaurant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRestaurantRepository)(nil).Update), ctx, restaurant)
}
