// Code generated by MockGen. DO NOT EDIT.
// Source: internal/restaurant/application/map_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/restaurant/application/map_client.go -destination=internal/restaurant/mocks/mock_map_service_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mapv1 "github.com/Leon180/tabelogo-v2/api/gen/map/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockMapServiceClient is a mock of MapServiceClient interface.
type MockMapServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMapServiceClientMockRecorder
	isgomock struct{}
}

// MockMapServiceClientMockRecorder is the mock recorder for MockMapServiceClient.
type MockMapServiceClientMockRecorder struct {
	mock *MockMapServiceClient
}

// NewMockMapServiceClient creates a new mock instance.
func NewMockMapServiceClient(ctrl *gomock.Controller) *MockMapServiceClient {
	mock := &MockMapServiceClient{ctrl: ctrl}
	mock.recorder = &MockMapServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapServiceClient) EXPECT() *MockMapServiceClientMockRecorder {
	return m.recorder
}

// QuickSearch mocks base method.
func (m *MockMapServiceClient) QuickSearch(ctx context.Context, placeID string) (*mapv1.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuickSearch", ctx, placeID)
	ret0, _ := ret[0].(*mapv1.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuickSearch indicates an expected call of QuickSearch.
func (mr *MockMapServiceClientMockRecorder) QuickSearch(ctx, placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuickSearch", reflect.TypeOf((*MockMapServiceClient)(nil).QuickSearch), ctx, placeID)
}
