// Code generated by MockGen. DO NOT EDIT.
// Source: internal/restaurant/application/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/restaurant/application/service.go -destination=internal/restaurant/mocks/mock_map_service_client.go -package=mocks -self_package=github.com/Leon180/tabelogo-v2/internal/restaurant/application MapServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mapv1 "github.com/Leon180/tabelogo-v2/api/gen/map/v1"
	model "github.com/Leon180/tabelogo-v2/internal/restaurant/domain/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRestaurantService is a mock of RestaurantService interface.
type MockRestaurantService struct {
	ctrl     *gomock.Controller
	recorder *MockRestaurantServiceMockRecorder
	isgomock struct{}
}

// MockRestaurantServiceMockRecorder is the mock recorder for MockRestaurantService.
type MockRestaurantServiceMockRecorder struct {
	mock *MockRestaurantService
}

// NewMockRestaurantService creates a new mock instance.
func NewMockRestaurantService(ctrl *gomock.Controller) *MockRestaurantService {
	mock := &MockRestaurantService{ctrl: ctrl}
	mock.recorder = &MockRestaurantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestaurantService) EXPECT() *MockRestaurantServiceMockRecorder {
	return m.recorder
}

// AddFavoriteTag mocks base method.
func (m *MockRestaurantService) AddFavoriteTag(ctx context.Context, userID, restaurantID uuid.UUID, tag string) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavoriteTag", ctx, userID, restaurantID, tag)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFavoriteTag indicates an expected call of AddFavoriteTag.
func (mr *MockRestaurantServiceMockRecorder) AddFavoriteTag(ctx, userID, restaurantID, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavoriteTag", reflect.TypeOf((*MockRestaurantService)(nil).AddFavoriteTag), ctx, userID, restaurantID, tag)
}

// AddFavoriteVisit mocks base method.
func (m *MockRestaurantService) AddFavoriteVisit(ctx context.Context, userID, restaurantID uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavoriteVisit", ctx, userID, restaurantID)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFavoriteVisit indicates an expected call of AddFavoriteVisit.
func (mr *MockRestaurantServiceMockRecorder) AddFavoriteVisit(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavoriteVisit", reflect.TypeOf((*MockRestaurantService)(nil).AddFavoriteVisit), ctx, userID, restaurantID)
}

// AddToFavorites mocks base method.
func (m *MockRestaurantService) AddToFavorites(ctx context.Context, userID, restaurantID uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFavorites", ctx, userID, restaurantID)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToFavorites indicates an expected call of AddToFavorites.
func (mr *MockRestaurantServiceMockRecorder) AddToFavorites(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFavorites", reflect.TypeOf((*MockRestaurantService)(nil).AddToFavorites), ctx, userID, restaurantID)
}

// CreateRestaurant mocks base method.
func (m *MockRestaurantService) CreateRestaurant(ctx context.Context, req CreateRestaurantRequest) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRestaurant", ctx, req)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRestaurant indicates an expected call of CreateRestaurant.
func (mr *MockRestaurantServiceMockRecorder) CreateRestaurant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRestaurant", reflect.TypeOf((*MockRestaurantService)(nil).CreateRestaurant), ctx, req)
}

// DeleteRestaurant mocks base method.
func (m *MockRestaurantService) DeleteRestaurant(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRestaurant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRestaurant indicates an expected call of DeleteRestaurant.
func (mr *MockRestaurantServiceMockRecorder) DeleteRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRestaurant", reflect.TypeOf((*MockRestaurantService)(nil).DeleteRestaurant), ctx, id)
}

// FindRestaurantsByCuisineType mocks base method.
func (m *MockRestaurantService) FindRestaurantsByCuisineType(ctx context.Context, cuisineType string, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRestaurantsByCuisineType", ctx, cuisineType, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRestaurantsByCuisineType indicates an expected call of FindRestaurantsByCuisineType.
func (mr *MockRestaurantServiceMockRecorder) FindRestaurantsByCuisineType(ctx, cuisineType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRestaurantsByCuisineType", reflect.TypeOf((*MockRestaurantService)(nil).FindRestaurantsByCuisineType), ctx, cuisineType, limit, offset)
}

// FindRestaurantsByLocation mocks base method.
func (m *MockRestaurantService) FindRestaurantsByLocation(ctx context.Context, lat, lng, radiusKm float64, limit int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRestaurantsByLocation", ctx, lat, lng, radiusKm, limit)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRestaurantsByLocation indicates an expected call of FindRestaurantsByLocation.
func (mr *MockRestaurantServiceMockRecorder) FindRestaurantsByLocation(ctx, lat, lng, radiusKm, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRestaurantsByLocation", reflect.TypeOf((*MockRestaurantService)(nil).FindRestaurantsByLocation), ctx, lat, lng, radiusKm, limit)
}

// GetFavoriteByUserAndRestaurant mocks base method.
func (m *MockRestaurantService) GetFavoriteByUserAndRestaurant(ctx context.Context, userID, restaurantID uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteByUserAndRestaurant", ctx, userID, restaurantID)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteByUserAndRestaurant indicates an expected call of GetFavoriteByUserAndRestaurant.
func (mr *MockRestaurantServiceMockRecorder) GetFavoriteByUserAndRestaurant(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteByUserAndRestaurant", reflect.TypeOf((*MockRestaurantService)(nil).GetFavoriteByUserAndRestaurant), ctx, userID, restaurantID)
}

// GetRestaurant mocks base method.
func (m *MockRestaurantService) GetRestaurant(ctx context.Context, id uuid.UUID) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurant", ctx, id)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurant indicates an expected call of GetRestaurant.
func (mr *MockRestaurantServiceMockRecorder) GetRestaurant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurant", reflect.TypeOf((*MockRestaurantService)(nil).GetRestaurant), ctx, id)
}

// GetRestaurantByExternalID mocks base method.
func (m *MockRestaurantService) GetRestaurantByExternalID(ctx context.Context, source model.RestaurantSource, externalID string) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestaurantByExternalID", ctx, source, externalID)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestaurantByExternalID indicates an expected call of GetRestaurantByExternalID.
func (mr *MockRestaurantServiceMockRecorder) GetRestaurantByExternalID(ctx, source, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestaurantByExternalID", reflect.TypeOf((*MockRestaurantService)(nil).GetRestaurantByExternalID), ctx, source, externalID)
}

// GetUserFavorites mocks base method.
func (m *MockRestaurantService) GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavorites", ctx, userID)
	ret0, _ := ret[0].([]*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavorites indicates an expected call of GetUserFavorites.
func (mr *MockRestaurantServiceMockRecorder) GetUserFavorites(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavorites", reflect.TypeOf((*MockRestaurantService)(nil).GetUserFavorites), ctx, userID)
}

// IncrementRestaurantViewCount mocks base method.
func (m *MockRestaurantService) IncrementRestaurantViewCount(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRestaurantViewCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRestaurantViewCount indicates an expected call of IncrementRestaurantViewCount.
func (mr *MockRestaurantServiceMockRecorder) IncrementRestaurantViewCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRestaurantViewCount", reflect.TypeOf((*MockRestaurantService)(nil).IncrementRestaurantViewCount), ctx, id)
}

// IsFavorite mocks base method.
func (m *MockRestaurantService) IsFavorite(ctx context.Context, userID, restaurantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFavorite", ctx, userID, restaurantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFavorite indicates an expected call of IsFavorite.
func (mr *MockRestaurantServiceMockRecorder) IsFavorite(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavorite", reflect.TypeOf((*MockRestaurantService)(nil).IsFavorite), ctx, userID, restaurantID)
}

// ListRestaurants mocks base method.
func (m *MockRestaurantService) ListRestaurants(ctx context.Context, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRestaurants", ctx, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRestaurants indicates an expected call of ListRestaurants.
func (mr *MockRestaurantServiceMockRecorder) ListRestaurants(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRestaurants", reflect.TypeOf((*MockRestaurantService)(nil).ListRestaurants), ctx, limit, offset)
}

// QuickSearchByPlaceID mocks base method.
func (m *MockRestaurantService) QuickSearchByPlaceID(ctx context.Context, placeID string) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuickSearchByPlaceID", ctx, placeID)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuickSearchByPlaceID indicates an expected call of QuickSearchByPlaceID.
func (mr *MockRestaurantServiceMockRecorder) QuickSearchByPlaceID(ctx, placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuickSearchByPlaceID", reflect.TypeOf((*MockRestaurantService)(nil).QuickSearchByPlaceID), ctx, placeID)
}

// RemoveFavoriteTag mocks base method.
func (m *MockRestaurantService) RemoveFavoriteTag(ctx context.Context, userID, restaurantID uuid.UUID, tag string) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavoriteTag", ctx, userID, restaurantID, tag)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFavoriteTag indicates an expected call of RemoveFavoriteTag.
func (mr *MockRestaurantServiceMockRecorder) RemoveFavoriteTag(ctx, userID, restaurantID, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavoriteTag", reflect.TypeOf((*MockRestaurantService)(nil).RemoveFavoriteTag), ctx, userID, restaurantID, tag)
}

// RemoveFromFavorites mocks base method.
func (m *MockRestaurantService) RemoveFromFavorites(ctx context.Context, userID, restaurantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromFavorites", ctx, userID, restaurantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromFavorites indicates an expected call of RemoveFromFavorites.
func (mr *MockRestaurantServiceMockRecorder) RemoveFromFavorites(ctx, userID, restaurantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromFavorites", reflect.TypeOf((*MockRestaurantService)(nil).RemoveFromFavorites), ctx, userID, restaurantID)
}

// SearchRestaurants mocks base method.
func (m *MockRestaurantService) SearchRestaurants(ctx context.Context, query string, limit, offset int) ([]*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRestaurants", ctx, query, limit, offset)
	ret0, _ := ret[0].([]*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRestaurants indicates an expected call of SearchRestaurants.
func (mr *MockRestaurantServiceMockRecorder) SearchRestaurants(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRestaurants", reflect.TypeOf((*MockRestaurantService)(nil).SearchRestaurants), ctx, query, limit, offset)
}

// UpdateFavoriteNotes mocks base method.
func (m *MockRestaurantService) UpdateFavoriteNotes(ctx context.Context, userID, restaurantID uuid.UUID, notes string) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavoriteNotes", ctx, userID, restaurantID, notes)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFavoriteNotes indicates an expected call of UpdateFavoriteNotes.
func (mr *MockRestaurantServiceMockRecorder) UpdateFavoriteNotes(ctx, userID, restaurantID, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavoriteNotes", reflect.TypeOf((*MockRestaurantService)(nil).UpdateFavoriteNotes), ctx, userID, restaurantID, notes)
}

// UpdateRestaurant mocks base method.
func (m *MockRestaurantService) UpdateRestaurant(ctx context.Context, id uuid.UUID, req UpdateRestaurantRequest) (*model.Restaurant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRestaurant", ctx, id, req)
	ret0, _ := ret[0].(*model.Restaurant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRestaurant indicates an expected call of UpdateRestaurant.
func (mr *MockRestaurantServiceMockRecorder) UpdateRestaurant(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRestaurant", reflect.TypeOf((*MockRestaurantService)(nil).UpdateRestaurant), ctx, id, req)
}

// MockMapServiceClient is a mock of MapServiceClient interface.
type MockMapServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMapServiceClientMockRecorder
	isgomock struct{}
}

// MockMapServiceClientMockRecorder is the mock recorder for MockMapServiceClient.
type MockMapServiceClientMockRecorder struct {
	mock *MockMapServiceClient
}

// NewMockMapServiceClient creates a new mock instance.
func NewMockMapServiceClient(ctrl *gomock.Controller) *MockMapServiceClient {
	mock := &MockMapServiceClient{ctrl: ctrl}
	mock.recorder = &MockMapServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapServiceClient) EXPECT() *MockMapServiceClientMockRecorder {
	return m.recorder
}

// QuickSearch mocks base method.
func (m *MockMapServiceClient) QuickSearch(ctx context.Context, placeID string) (*mapv1.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuickSearch", ctx, placeID)
	ret0, _ := ret[0].(*mapv1.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuickSearch indicates an expected call of QuickSearch.
func (mr *MockMapServiceClientMockRecorder) QuickSearch(ctx, placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuickSearch", reflect.TypeOf((*MockMapServiceClient)(nil).QuickSearch), ctx, placeID)
}
